data_sources:
  gpdb:
    - host: "chorus-gpdb42"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

    - host: "chorus-gpdb41"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

    - host: "chorus-gpdb40"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

    - host: "local-greenplum"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "vagrant"
        db_password: "secret"

    - host: "chorus-gpdb-ci"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

    - host: "alpine-gpdb"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

  hadoop:
    - host: "alpine-hadoop"
      port: "8200"
      username: "alpine"
      group_list: "supergroup"
      hdfs_version: "Apache Hadoop 0.20.2"

    - host: "chorus-gphd02"
      port: 8020
      username: "pivotal"
      hdfs_version: "Greenplum HD 0.20"

    - host: "chorus-gphd11"
      port: 8020
      username: "hadoop"
      hdfs_version: "Greenplum HD 1.1"

  oracle:
    - host: "chorus-oracle"
      port: 1521
      db_name: "orcl11g"
      account:
        db_username: "system"
        db_password: "password"
  hawq:
    - host: "chorus-gphd20-2"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"