data_sources:
  gpdb:
    - host: "chorus-gpdb42"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

    - host: "chorus-gpdb41"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

    - host: "chorus-gpdb40"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "gpadmin"
        db_password: "secret"

    - host: "local-greenplum"
      port: 5432
      db_name: "postgres"
      account:
        db_username: "vagrant"
        db_password: "secret"

  hadoop:
    - host: "chorus-gphd02"
      port: 8020
      username: "pivotal"

  oracle:
    - host: "chorus-oracle"
      port: 1521
      db_name: "orcl"
      account:
        db_username: "system"
        db_password: "oracle"