#Only defaults that should apply to all applications should go in here, optional configurations should only go into chorus.yml.example
session_timeout_minutes: 120
instance_poll_interval_minutes: 5
delete_unimported_csv_files_interval_hours: 6
delete_unimported_csv_files_after_hours: 24
reindex_datasets_interval_hours: 24
csv_import_file_storage_path: ":rails_root/system/"
workfile_storage_path : ":rails_root/system/"
image_storage: ":rails_root/system/"
attachment_storage: ":rails_root/system/"
max_upload_size_megabytes: 100
server_port: 8080
provision_max_size_in_gb: 100
timezone_offset: -8
worker_threads: 5
file_sizes_mb:
  workfiles: 10
  csv_imports: 10
  user_icon: 5
  workspace_icon: 5
  note_attachment: 10
  max_upload_size_megabytes: 100
