# Don't forget to add your new key to chorus.yml.example AND chorus.defaults.yml AND chorus.yml in chorus-staging server (if it should be different from the defaults)!!!
session_timeout_minutes: 120
instance_poll_interval_minutes: 5
delete_unimported_csv_files_interval_hours: 1
delete_unimported_csv_files_after_hours: 12
reindex_datasets_interval_hours: 24
csv_import_file_storage_path: ":rails_root/system/"
workfile_storage_path : ":rails_root/system/"
image_storage: ":rails_root/system/"
attachment_storage: ":rails_root/system/"
server_port: 8080
provision_max_size_in_gb: 100
timezone_offset: -8
file_sizes_mb:
  workfiles:  10
  csv_imports:  10
  max_upload_size_megabytes: 100

gpfdist:
  ssl: false
  url: "chorus-staging"
  write_port: 8000
  read_port: 8001
  data_dir: "/tmp"

ldap:
  host: 10.32.88.212
  enable: false
  port: 389
  connect_timeout: 10000
  bind_timeout: 10000
  search:
    timeout: 20000
    size_limit: 200
  base: DC=greenplum,DC=com
  user_dn:
  password:
  dn_template: greenplum\{0}
  attribute:
    uid: sAMAccountName
    ou: department
    gn: givenName
    sn: sn
    cn: cn
    mail: userprincipalname
    title: title


aurora:
# Aurora CMS Admin
  aurora_admin_user: bliu@pivotallabs.com
  # please set the password before Aurora deployment
  # if you want to use a specific password. Otherwise, an internal password is set.
  aurora_admin_password: secret
  aurora_admin_first_name: Brandon
  aurora_admin_last_name: Liu
  aurora_admin_phone_number: (415) 555-1234
  aurora_admin_email: admin@aurora.com

  # default resource bundle will be created in CMS
  target_rb_name: RB

  # default organization will be created in CMS
  target_org_name: ORG

  # default database group will be created in CMS
  target_dbg_name: DBG

  # indicate that if aurora initialized or not
  aurora_initialized: true

  # Aurora's service URL
  aurora_service_url: https://10.80.129.96/datadirector/services/datacloudWS

  # gpfdist settings
  gpfdist_port: 8081
  gpfdist_data_dir: /opt/chorus/gpdata/gpfdist/

  # Connection mgmt
  # Connection timeout in milliseconds
  connection_timeout: 60000

  # Max concurrent connection #
  max_connection: 100

  # Time in milliseconds to get a connection from pool
  connection_pool_timeout: 60000