---
default:
  adapter: jdbcpostgresql
  encoding: unicode
  username: edcadmin
  password:
  port: 8543
  min_messages: warning
  host: 127.0.0.1
  pool: 20
development:
  database: chorus_rails_development
  adapter: jdbcpostgresql
  encoding: unicode
  username: edcadmin
  password:
  port: 8543
  min_messages: warning
  host: 127.0.0.1
  pool: 20
test:
  database: chorus_rails_test
  adapter: jdbcpostgresql
  encoding: unicode
  username: edcadmin
  password:
  port: 8543
  min_messages: warning
  host: 127.0.0.1
  pool: 20
integration:
  database: chorus_rails_integration
  adapter: jdbcpostgresql
  encoding: unicode
  username: edcadmin
  password:
  port: 8543
  min_messages: warning
  host: 127.0.0.1
  pool: 20
production:
  database: chorus_rails_production
  adapter: jdbcpostgresql
  encoding: unicode
  username: pivotal
  password:
  port: 8543
  min_messages: warning
  host: 127.0.0.1
  pool: 20
packaging:
  database: chorus_rails_packaging
  adapter: jdbcpostgresql
  encoding: unicode
  username: edcadmin
  password:
  port: 8543
  min_messages: warning
  host: 127.0.0.1
  pool: 20
...
