stage: &stage
  host: chorus-staging
  install_path: ~/chorusrails-deploy-new
  postgres_build: 2

upgrade21:
  host: chorus-chorus21-upgrade
  legacy_path: ~/chorus
  postgres_build: 2
  install_path: ~/chorusrails
  legacy_data_host: chorus-chorus21

fresh_install:
  host: chorus-freshinstall
  postgres_build: 2
  install_path: ~/chorusrails_freshinstall
  clean_install: true

load_test:
  <<: *stage
  host: chorus-load-test
  install_path: ~/chorus

vprevious:
  host: chorus-vprevious
  install_path: ~/chorus
  postgres_build: 2

vnext:
  host: chorus-vnext
  install_path: ~/chorus
  postgres_build: 2