jruby: http://jruby.org.s3.amazonaws.com/downloads/1.7.11/jruby-complete-1.7.11.jar
jetty: http://dist.codehaus.org/jetty/jetty-hightide-8.1.14/jetty-hightide-8.1.14.v20131031.zip
jruby_rack: http://repository.codehaus.org/org/jruby/rack/jruby-rack/1.1.14/jruby-rack-1.1.14.jar
app_root: $CHORUS_HOME
java_options: $CHORUS_JAVA_OPTIONS
ruby_version: 1.9
app_type: rack
http_port: 3000
bundle_without: [integration, development, test, packaging, ci_jasmine, ci_legacy, ci_next]
max_concurrent_connections: 20
