# uncomment the 'host' key to enable ldap
# in the development/test environments

ldap:
  host: #bartol.sf.pivotallabs.com
  dc: bartol
  cn: users
  dn:
    template: greenplum\\{0}
  attribute_names:
    sn: sn
    ou: departmentnumber
    gn: givenName
    mail: mail
    title: title
    uid: uid
